### ISSUE TITLE
Plan for update or official c++ SDK for DocumentDB

### ISSUE THREAD

**Issue by pherbel** [stalker314314/DocumentDBCpp#7]
Hi,

Is there any plan to develop and update this package or official c++ sdk?
We are looking for a C++ library for DocumentDb and it seems there is no real alternative.
Maybe do you know and other option?

Thank you.

**Comment by stalker314314** [comment]
Currently, there is no plan to update this package further. However, I just might find spare time to add new things you might request. I am not aware of any other option. That being said, you are free to take this wrapper and improve on top of it, if that's option for you!
