### ISSUE TITLE
newer api version

### ISSUE THREAD

**Issue by asebak** [stalker314314/DocumentDBCpp#9]
Getting this error when querying collections:

The collection '<name>' could not be read because it was created with a newer API version.

**Comment by stalker314314** [comment]
Oh, not again:) I hope it is just a matter of bumping HEADER_MS_VERSION in https://github.com/stalker314314/DocumentDBCpp/blob/master/lib/src/ConnectionHelper.cpp#L120, but I am not sure. If you have time, canyou hack some value from here: https://docs.microsoft.com/en-us/rest/api/documentdb/#supported-rest-api-versions?

**Comment by asebak** [comment]
when building the solution I get  a lot of these errors:

Error	C3861	'_wassert': identifier not found	test.cpp	68

**Comment by asebak** [comment]
couldn't really get the project setup, there's also some compiling issues in the test project.  After fixing that it compile but all the apis were crashing even without changing your existing code.  I believe it had something to do with my setup potentially.  Can you try this out?

**Comment by stalker314314** [comment]
I will bump to latest version, so any DB created from outside of DocumentDbCPP will work. However, some stuff changed in API and now I am going fixing it piece by piece, expect updates soon!

**Comment by stalker314314** [comment]
I just made all necessary changes to support latest API version. If you sync again, you will be able to work with DBs created outside of DocumentDBCpp, regardless of how they are created. I didn't release nuget yet, thought, but I guess you can try without it too. Let me know if you want to be pinged when I release nuget. I will close this issue as I think this should be fixed
